// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace Repository.Migrations
{
    [DbContext(typeof(ProductManagementDBContext))]
    partial class ProductManagementDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ManufactureDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAvailable = true,
                            ManufactureDate = new DateTime(2024, 4, 9, 12, 47, 29, 385, DateTimeKind.Utc).AddTicks(5775),
                            Name = "Shoes",
                            Price = 500m,
                            StockCount = 50
                        },
                        new
                        {
                            Id = 2,
                            IsAvailable = true,
                            ManufactureDate = new DateTime(2024, 4, 9, 12, 47, 29, 385, DateTimeKind.Utc).AddTicks(5779),
                            Name = "T-Shirt",
                            Price = 200m,
                            StockCount = 100
                        },
                        new
                        {
                            Id = 3,
                            IsAvailable = false,
                            ManufactureDate = new DateTime(2024, 4, 9, 12, 47, 29, 385, DateTimeKind.Utc).AddTicks(5780),
                            Name = "Jeans",
                            Price = 600m,
                            StockCount = 80
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
